engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      - javascript
## exclude external library builds
exclude_paths:
- "lib/*"
- "dist/*"
- "test/**/*"
- "examples/**/*"
- "scripts/**/*"